In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.datasets import load_boston
from sklearn.metrics import mean_squared_error

In [ ]:
boston=load_boston()

In [ ]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [ ]:
df=pd.DataFrame(boston.data,columns=boston.feature_names)
df

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

In [ ]:
df.isnull()

CRIM     ZN  INDUS   CHAS    NOX  ...    RAD    TAX  PTRATIO      B  LSTAT
0    False  False  False  False  False  ...  False  False    False  False  False
1    False  False  False  False  False  ...  False  False    False  False  False
2    False  False  False  False  False  ...  False  False    False  False  False
3    False  False  False  False  False  ...  False  False    False  False  False
4    False  False  False  False  False  ...  False  False    False  False  False
..     ...    ...    ...    ...    ...  ...    ...    ...      ...    ...    ...
501  False  False  False  False  False  ...  False  False    False  False  False
502  False  False  False  False  False  ...  False  False    False  False  False
503  False  False  False  False  False  ...  False  False    False  False  False
504  False  False  False  False  False  ...  False  False    False  False  False
505  False  False  False  False  False  ...  False  False    False  False  False

[506 rows x 13 columns]

In [ ]:
target=pd.DataFrame(boston.target,columns=['target'])
target

target
0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
..      ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9

[506 rows x 1 columns]

In [ ]:
df.describe().round(decimals=2)

CRIM      ZN   INDUS    CHAS  ...     TAX  PTRATIO       B   LSTAT
count  506.00  506.00  506.00  506.00  ...  506.00   506.00  506.00  506.00
mean     3.61   11.36   11.14    0.07  ...  408.24    18.46  356.67   12.65
std      8.60   23.32    6.86    0.25  ...  168.54     2.16   91.29    7.14
min      0.01    0.00    0.46    0.00  ...  187.00    12.60    0.32    1.73
25%      0.08    0.00    5.19    0.00  ...  279.00    17.40  375.38    6.95
50%      0.26    0.00    9.69    0.00  ...  330.00    19.05  391.44   11.36
75%      3.68   12.50   18.10    0.00  ...  666.00    20.20  396.22   16.96
max     88.98  100.00   27.74    1.00  ...  711.00    22.00  396.90   37.97

[8 rows x 13 columns]

In [ ]:
reg=linear_model.LinearRegression()
reg.fit(df,target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
reg.coef_

array([[-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,
         2.68673382e+00, -1.77666112e+01,  3.80986521e+00,
         6.92224640e-04, -1.47556685e+00,  3.06049479e-01,
        -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
        -5.24758378e-01]])

In [ ]:
reg.intercept_

array([36.45948839])

In [ ]:
test=boston.data[-30:]

In [ ]:
test

array([[4.87141e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.14000e-01,
        6.48400e+00, 9.36000e+01, 2.30530e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.96210e+02, 1.86800e+01],
       [1.50234e+01, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.14000e-01,
        5.30400e+00, 9.73000e+01, 2.10070e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.49480e+02, 2.49100e+01],
       [1.02330e+01, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.14000e-01,
        6.18500e+00, 9.67000e+01, 2.17050e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.79700e+02, 1.80300e+01],
       [1.43337e+01, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.14000e-01,
        6.22900e+00, 8.80000e+01, 1.95120e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.83320e+02, 1.31100e+01],
       [5.82401e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 5.32000e-01,
        6.24200e+00, 6.47000e+01, 3.42420e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.96900e+02, 1.07400e+01],
       [5.70818e+00, 0.00000e+

In [ ]:
predicted=reg.predict(test)

In [ ]:
predicted

array([[20.534816  ],
       [11.54272738],
       [19.20496304],
       [21.86276391],
       [23.46878866],
       [27.09887315],
       [28.56994302],
       [21.08398783],
       [19.45516196],
       [22.22225914],
       [19.65591961],
       [21.32536104],
       [11.85583717],
       [ 8.22386687],
       [ 3.66399672],
       [13.75908538],
       [15.93118545],
       [20.62662054],
       [20.61249414],
       [16.88541964],
       [14.01320787],
       [19.10854144],
       [21.29805174],
       [18.45498841],
       [20.46870847],
       [23.53334055],
       [22.37571892],
       [27.6274261 ],
       [26.12796681],
       [22.34421229]])

In [ ]:
test1=boston.target[-30:]

In [ ]:
test1

array([16.7, 12. , 14.6, 21.4, 23. , 23.7, 25. , 21.8, 20.6, 21.2, 19.1,
       20.6, 15.2,  7. ,  8.1, 13.6, 20.1, 21.8, 24.5, 23.1, 19.7, 18.3,
       21.2, 17.5, 16.8, 22.4, 20.6, 23.9, 22. , 11.9])

In [ ]:
print("mean squared error is:",mean_squared_error(test1,predicted))

mean squared error is: 12.041884621640149
